version: 1.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
platform: x86
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/BorderlessFullscreen.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd data

    release.bat
artifacts:
- path: data/BorderlessFullscreen.zip
  name: BorderlessFullscreen.zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: BorderlessFullscreen v$(appveyor_build_version)
  description: '- [Readme](https://github.com/ThirteenAG/III.VC.SA.WindowedMode/blob/v1.0/README.md)'
  auth_token:
    secure: SXMI7bm5RKh5j1S8A8dnUP2HFw97xHHlJH+mA0hx819vtxOPCpMFY3aFZ+2v16ri
  artifact: BorderlessFullscreen.zip